#!/bin/sh
# Skript to format and filter the lynx textdump
sed -nf ~/.gamefaqs/filter  $1 >> $GTMP/tmp
sed -e :a -e '$!N;s/\nhttp/ http/;ta' -e 'P;D' $GTMP/tmp | sort -n >> $2
#'/469050\|924363\|924364\|927345/{p;n;p}'
